config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :spaces, only: [:index, :show, :new, :create, :destroy] do
    resources :reservations, only: [:create]
    collection do
      get 'own_spaces' #this would be the controller action
      # get "reservations/:reservation_id/reviews", to: "reviews#index"
    end
  end

  resources :reservations, only: [:create, :new] do
    resources :payments, only: :new
    resources :reviews,  only: [:create, :new]
  end

  resources :users, only: [:index, :show, :create, :new] do
    resources :reservations, only: [:index]
    resources :spaces, only: [:index]
  end

  resources :reservations, only: [:show] do #In this case it has to be outside because of the path
    collection do
      get 'own_reservations'
    end
  end

  if Rails.env.development?
    get 'kitchen_sink', to: 'pages#kitchen_sink'
  end

  resources :orders, only: [:show, :create]
end

app/models/space.rb
class Space < ApplicationRecord
  has_one_attached :photo

  has_many :reservations, dependent: :destroy
  has_many :reviews, through: :reservations
  has_many :space_tags
  has_many :tags, through: :space_tags


  belongs_to :user

  geocoded_by :full_address
  after_validation :geocode, if: :will_save_change_to_address?

  validates :name, :address, :price_per_day, :city, :content, presence: true
  monetize :price_per_day_cents
  def full_address
    "#{address} - #{city}"
  end

  def sku
    "#{self.class.name.parameterize}-#{id}"
  end

  def booked_by?(user)
    reservations.any? do |reservation|
      reservation.user == user
    end
  end

  def all_tags=(names)
    # names = %w(paiting woodwork film photo recording sculpting)
    # Purpose of this method is to push the tag.name into an array that belongs to the space itself
    self.tags = names.split(',').map do |name|
      Tag.where(name: name).first_or_create!
      # SpaceTag.create(tag: tag, space: self) if tag
    end
  end

  def all_tags
    tags.map(&:name)
    end
end

app/controllers/spaces_controller.rb
#require 'pry'
class SpacesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    if params[:query].present?
      sql_query = "city ILIKE :query OR address ILIKE :query"
      @spaces = Space.geocoded.where(sql_query, query: "%#{params[:query]}%")
    else
      @spaces = Space.geocoded
    end

    @markers = @spaces.map do |space|
      {
        id: space.id,
        lat: space.latitude,
        lng: space.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { space: space }),
      }
    end
  end

  def show
    @spaces = Space.first(3)
    @space = Space.find(params[:id])
    @reservation = Reservation.new
  end

  def new
    @space = Space.new
    @user = current_user
  end

  def create
    @space = Space.new(space_params)
    @user = User.new(params[:user_id])
    @space.user = @user
    tags = params["space"]["tag_ids"]
    tags.each do |tag|
      if tag != ""
        tag_instance = Tag.find(tag.to_i)
        SpaceTag.create(space: @space, tag: tag_instance)
      end
    end
    if @space.save
      redirect_to spaces_path
    else
      render :new
    end
  end

  def own_spaces
    @spaces = Space.where(user: current_user)
  end

  private

  def space_params
    params.require(:space).permit(:name, :address, :price_per_day, :city, :content, :photo)
  end
end

app/views/spaces/_card.html.erb
<%= link_to space_path(space),  class: "card space-card box-shadow" do %>
  <% if space.photo.attached? %>
    <%= cl_image_tag space.photo.key, height: 250, width: 500, crop: :fill, class: "card-img-top" %>
  <% else %>
    <img class="card-img-top" alt="image" src="https://source.unsplash.com/featured/<%= rand(2000) %>/?art" data-holder-rendered="true">
  <% end %>
  <div class="card-body d-flex flex-column pt-2 pb-8 px-2">
    <h3><%= space.name %></h3>
    <p class="card-text"><%= space.address %>, <%= space.city %> </p>
    <p class="card-text-price">$<%= space.price_per_day %> per day</p>
    <div class="d-flex justify-content-between">
      <div class="btn-group mt-auto ">
      <%#= link_to  "view", space_path(space), class: "btn btn-primary " %>
      </div>
    </div>
  </div>
<% end %>

app/views/spaces/_info_window.html.erb
<h2><%= space.name %></h2>
<p><%= space.address %></p>

app/views/spaces/index.html.erb
<div class="d-flex align-items-start">
  <div class="cards-grid p-3 flex-grow-1">
    <% @spaces.each do |space| %>
      <%= render 'card', space: space %>
    <% end %>
  </div>
  <div
    id="map"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>

app/views/spaces/new.html.erb
<%= render "shared/post_form"%>

app/views/spaces/own_spaces.html.erb
<h2 style="text-align:center; padding-top:30px">My Studioos</h2>
<div class="d-flex align-items-start">
  <div class="cards-grid p-3 flex-grow-1">
    <% @spaces.each do |space| %>
      <%= render 'card', space: space %>
    <% end %>
  </div>
</div>

app/views/spaces/show.html.erb
<!-- Slider -->
<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="d-block w-100 carousel-full-height-image" src="https://res.cloudinary.com/pcobos85/image/upload/v1584138442/photostudio1.jpg" alt="First slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100 carousel-full-height-image" src="https://res.cloudinary.com/pcobos85/image/upload/v1584138443/photostudio2.png" alt="Second slide">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
<!-- /slider -->

<!-- studio info -->
<div class="border-bottom-light bg-white">
  <div class="container py-3">
    <div class="row">
      <div class="col-md-8 p-3">
        <h3><%= @space.name %></h3>
        <img src="https://res.cloudinary.com/doytwihfl/image/upload/v1582928012/Screen_Shot_2020-02-28_at_17.12.41_fjxzxh.png" alt="reviews">
        <p>
          <%= @space.content %> <a href="#">Read more</a>
        </p>

        <!-- Rentals -->
          <div class="card card p-3 mb-3">
            <h5><strong>STUDIO USE</strong></h5>
            <div class="center">
            <ul class="list-inline tags">
            <% @space.tags.each do |tag| %>
            <li id="tag" class="fas fa-tag badge badge-dark mr-0 list-inline-item">&nbsp;&nbsp;<span class="tag-text"><%=tag.name%></span></li>
          <% end %>
          </ul>
          </div>
          </div>
          <div class="card card p-3 mb-3">
            <h5><strong>STUDIO INFORMATION</strong></h5>
            <p><small>Size: 32 m²</small></p>
            <p><small>Type: private</small></p>
            <p><small>Rental Period (Min): 30 Days</small></p>
          </div>
          <div class="card card p-3 mb-3">
            <h5><strong>FACILITIES</strong></h5>
            <p><small>Desk</small></p>
            <p><small>Kitchen</small></p>
            <p><small>Water</small></p>
            <p><small>Windows</small></p>
            <p><small>Electricity</small></p>
            <p><small>Wifi</small></p>
          </div>
          <div class="card card p-3 mb-3">
            <h5><strong>ACCESS</strong></h5>
            <p><small>Parking</small></p>
            <p><small>Public Transport</small></p>
            <p><small>Wheel chair access</small></p>
          </div>
          <img src="https://res.cloudinary.com/doytwihfl/image/upload/v1582928363/Screen_Shot_2020-02-28_at_17.17.06_aagnlh.png" alt="reviews">


      <dl>
        <% @space.reviews.each do |review| %>
          <dt><%= review.content %></dt>
          <dd><%= review.ratings %></dd>
        <% end %>
      </dl>

      <% if @space.booked_by?(current_user)  %>
      <% end %>
      <h2>Recommended spaces</h2>
       <div class="cards-grid p-3 flex-grow-1">
          <% @spaces.each do |space| %>
          <%= render '/spaces/card', space: space %>
          <% end %>
      </div>
      </div>





      <div class="col-md-4">
        <!-- checkout -->
        <div class="card p-3 m-3  stick">
          <div class="d-flex align-items-center mt-3">
            <p><strong><h2>$<%= @space.price_per_day %>/day</h2></strong></p>
          </div>
          <div class="d-flex align-items-center mt-1">
            <p><%= @space.address %>, <%= @space.city %></p>
          </div>
          <h5 class="mt-3 mb-3">Book this space</h5>
          <%= simple_form_for [@space, @reservation] do |f| %>
            <%= f.input :start_on %>
            <%= f.input :end_on %>
            <%= f.submit "Confirm", class: "btn btn-primary btn-block" %>
          <% end %>
        </div>
      </div>

    </div>
  </div>
</div>
      <!-- /checkout -->

<!-- /studio info -->

<!-- studio checkout-->