config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :spaces, only: [:index, :show, :new, :create, :destroy] do
    resources :reservations, only: [:create]
    collection do
      get 'own_spaces' #this would be the controller action
      # get "reservations/:reservation_id/reviews", to: "reviews#index"
    end
  end

  resources :reservations, only: [:create, :new] do
    resources :payments, only: :new
    resources :reviews,  only: [:create, :new]
  end

  resources :users, only: [:index, :show, :create, :new] do
    resources :reservations, only: [:index]
    resources :spaces, only: [:index]
  end

  resources :reservations, only: [:show] do #In this case it has to be outside because of the path
    collection do
      get 'own_reservations'
    end
  end

  if Rails.env.development?
    get 'kitchen_sink', to: 'pages#kitchen_sink'
  end

  resources :orders, only: [:show, :create]
end

app/views/shared/_back_to_top.html.erb
<!-- Go to Top -->
  <a class="js-go-to u-go-to" href="javascript:;"
    data-position='{"bottom": 15, "right": 15 }'
    data-type="fixed"
    data-offset-top="400"
    data-compensation="#header"
    data-show-effect="slideInUp"
    data-hide-effect="slideOutDown">
    <i class="fa fa-arrow-up u-go-to__inner"></i>
  </a>
  <!-- End Go to Top -->

app/views/shared/_footer.html.erb
<!-- ========== FOOTER ========== -->
  <footer class="bgxp pt-9 mb-0">
    <div class="container space-2">
      <div class="row justify-content-md-between">
        <div class="col-6 col-md-3 col-lg-2 order-lg-3 mb-7 mb-lg-0">
          <h3 class="h6 text-white mb-3">About</h3>

          <!-- List Group -->
          <div class="list-group list-group-flush list-group-transparent">
            <a class="list-group-item list-group-item-action" href="../pages/about-agency.html">About Agency</a>
            <a class="list-group-item list-group-item-action" href="../pages/about-start-up.html">About Start-Up</a>
            <a class="list-group-item list-group-item-action" href="../pages/services-agency.html">Services Agency</a>
            <a class="list-group-item list-group-item-action" href="../pages/services-start-up.html">Services Start-Up</a>
          </div>
          <!-- End List Group -->
        </div>

        <div class="col-6 col-md-3 col-lg-2 order-lg-4 mb-7 mb-lg-0">
          <h3 class="h6 text-white mb-3">Company</h3>

          <!-- List Group -->
          <div class="list-group list-group-flush list-group-transparent">
            <a class="list-group-item list-group-item-action" href="../pages/contacts-agency.html">Contact Us</a>
            <a class="list-group-item list-group-item-action" href="../pages/help.html">Help</a>
            <a class="list-group-item list-group-item-action" href="../pages/careers.html">Careers</a>
            <a class="list-group-item list-group-item-action" href="../pages/terms.html">Terms &amp; Conditions</a>
            <a class="list-group-item list-group-item-action" href="../pages/privacy.html">Privacy &amp; Policy</a>
          </div>
          <!-- End List Group -->
        </div>

        <div class="col-6 col-md-3 col-lg-2 order-lg-5 mb-7 mb-lg-0">
          <h3 class="h6 text-white mb-3">Shop</h3>

          <!-- List Group -->
          <div class="list-group list-group-flush list-group-transparent">
            <a class="list-group-item list-group-item-action" href="../shop/classic.html">Classic</a>
            <a class="list-group-item list-group-item-action" href="../shop/single-product.html">Single Product</a>
            <a class="list-group-item list-group-item-action" href="../shop/checkout.html">Checkout</a>
          </div>
          <!-- End List Group -->
        </div>

        <div class="col-6 col-md-3 col-lg-2 order-lg-6 mb-7 mb-lg-0">
          <h3 class="h6 text-white mb-3">Social</h3>

          <!-- List -->
          <div class="list-group list-group-flush list-group-transparent">
            <a class="list-group-item list-group-item-action" href="#">
              <i class="fab fa-facebook-f min-width-3 text-center mr-2"></i>
              Facebook
            </a>
            <a class="list-group-item list-group-item-action" href="#">
              <i class="fab fa-twitter min-width-3 text-center mr-2"></i>
              Twitter
            </a>
            <a class="list-group-item list-group-item-action" href="#">
              <i class="fab fa-dribbble min-width-3 text-center mr-2"></i>
              Dribbble
            </a>
            <a class="list-group-item list-group-item-action" href="#">
              <i class="fab fa-github min-width-3 text-center mr-2"></i>
              GitHub
            </a>
          </div>
          <!-- End List -->
        </div>

        <div class="col-lg-4 order-lg-1 d-flex align-items-start flex-column">
          <!-- Logo -->
          <a class="d-inline-block mb-5" href="studioo.space" aria-label="Space">
            <img src="https://res.cloudinary.com/daak4feoa/image/upload/v1584123073/fav_bicjth.png" alt="Logo" style="width: 40px; max-width: 100%;">
          </a>
          <!-- End Logo -->

          <!-- Language -->
          <div class="btn-group d-block position-relative mb-4 mb-lg-auto">
            <a id="footerLanguageInvoker" class="btn-text-secondary d-flex align-items-center u-unfold--language-btn rounded py-2 px-3" href="javascript:;" role="button"
               aria-controls="footerLanguage"
               aria-haspopup="true"
               aria-expanded="false"
               data-unfold-event="click"
               data-unfold-target="#footerLanguage"
               data-unfold-type="css-animation"
               data-unfold-duration="300"
               data-unfold-delay="300"
               data-unfold-hide-on-scroll="false"
               data-unfold-animation-in="slideInUp"
               data-unfold-animation-out="fadeOut">
              <span class="font-size-14">English</span>
              <i class="fa fa-angle-down u-unfold__icon-pointer u-unfold--language-icon-pointer ml-4"></i>
            </a>

            <!-- Content -->
            <div id="footerLanguage" class="u-unfold u-unfold--language bottom-0 left-0" aria-labelledby="footerLanguageInvoker">
              <div class="py-6 px-5">
                <h4 class="h6 mb-4">Select your language</h4>

                <div class="row">
                  <div class="col-6">
                  <!-- List of Languages -->
                    <div class="list-group list-group-borderless list-group-flush">
                      <a class="active d-flex align-items-center list-group-item list-group-item-action" href="#">
                        <img class="max-width-3 mr-2" src="../../theme/vendor/flag-icon-css/flags/4x3/us.svg" alt="United States Flag">
                        English
                      </a>
                      <a class="d-flex align-items-center list-group-item list-group-item-action" href="#">
                        <img class="max-width-3 mr-2" src="../../theme/vendor/flag-icon-css/flags/4x3/fr.svg" alt="France Flag">
                        Français
                      </a>
                      <a class="d-flex align-items-center list-group-item list-group-item-action" href="#">
                        <img class="max-width-3 mr-2" src="../../theme/vendor/flag-icon-css/flags/4x3/de.svg" alt="Germany Flag">
                        Deutsch
                      </a>
                      <a class="d-flex align-items-center list-group-item list-group-item-action" href="#">
                        <img class="max-width-3 mr-2" src="../../theme/vendor/flag-icon-css/flags/4x3/pt.svg" alt="Portugal Flag">
                        Português
                      </a>
                    </div>
                    <!-- End List of Languages -->
                  </div>

                  <div class="col-6">
                    <!-- List of Languages -->
                    <div class="list-group list-group-borderless list-group-flush">
                      <a class="d-flex align-items-center list-group-item list-group-item-action" href="#">
                        <img class="max-width-3 mr-2" src="../../theme/vendor/flag-icon-css/flags/4x3/es.svg" alt="Spain Flag">
                        Español
                      </a>
                      <a class="d-flex align-items-center list-group-item list-group-item-action" href="#">
                        <img class="max-width-3 mr-2" src="../../theme/vendor/flag-icon-css/flags/4x3/it.svg" alt="Italy Flag">
                        Italiano
                      </a>
                      <a class="d-flex align-items-center list-group-item list-group-item-action" href="#">
                        <img class="max-width-3 mr-2" src="../../theme/vendor/flag-icon-css/flags/4x3/ru.svg" alt="Russian Flag">
                        Русский
                      </a>
                      <a class="d-flex align-items-center list-group-item list-group-item-action" href="#">
                        <img class="max-width-3 mr-2" src="../../theme/vendor/flag-icon-css/flags/4x3/tr.svg" alt="Turkey Flag">
                        Türkçe
                      </a>
                    </div>
                    <!-- End List of Languages -->
                  </div>
                </div>
              </div>

              <!-- Signup -->
              <a class="u-unfold--language__link p-5" href="../pages/signup-simple.html">
                <small class="d-block text-muted mb-1">More languages coming soon.</small>
                <small class="d-block">Signup to get notified <i class="fa fa-arrow-right u-unfold__icon-pointer"></i></small>
              </a>
              <!-- End Signup -->
            </div>
            <!-- End Content -->
          </div>
          <!-- End Language -->

          <p class="small text-muted">All rights reserved. &copy; Studioo.space. 2020 Brogrammers.</p>
        </div>
      </div>
    </div>
</footer>

app/views/shared/_gallery_profile.html.erb
<!-- Grid row -->
<div class="gallery pt-5" id="gallery">

  <!-- Grid column -->
  <div class="mb-3 pics animation all 2">
    <img class="img-fluid" src="https://mdbootstrap.com/img/Photos/Horizontal/Nature/4-col/img%20(73).jpg" alt="Card image cap">
  </div>
  <!-- Grid column -->

  <!-- Grid column -->
  <div class="mb-3 pics animation all 1">
    <img class="img-fluid" src="https://mdbootstrap.com/img/Photos/Vertical/mountain1.jpg" alt="Card image cap">
  </div>
  <!-- Grid column -->

  <!-- Grid column -->
  <div class="mb-3 pics animation all 1">
    <img class="img-fluid" src="https://mdbootstrap.com/img/Photos/Vertical/mountain2.jpg" alt="Card image cap">
  </div>
  <!-- Grid column -->

  <!-- Grid column -->
  <div class="mb-3 pics animation all 2">
    <img class="img-fluid" src="https://mdbootstrap.com/img/Photos/Horizontal/Nature/4-col/img%20(35).jpg" alt="Card image cap">
  </div>
  <!-- Grid column -->

  <!-- Grid column -->
  <div class="mb-3 pics animation all 2">
    <img class="img-fluid" src="https://mdbootstrap.com/img/Photos/Horizontal/Nature/4-col/img%20(18).jpg" alt="Card image cap">
  </div>
  <!-- Grid column -->

  <!-- Grid column -->
  <div class="mb-3 pics animation all 1">
    <img class="img-fluid" src="https://mdbootstrap.com/img/Photos/Vertical/mountain3.jpg" alt="Card image cap">
  </div>
  <!-- Grid column -->

</div>
<!-- Grid row -->

app/views/shared/_header_search.html.erb
<!-- ========== MAIN CONTENT ========== -->
<main id="content">
  <video autoplay muted loop id="myVideo">
    <source src="https://res.cloudinary.com/dvlgiurta/video/upload/v1584121335/studioo/mixkit-paint-covered-woman-stands-in-front-of-mural-911_fk5wmq.mp4" type="video/mp4">
  </video>
  <!-- Hero Section -->
  <div class="gradient-overlay-dark-v1 bg-img-hero overflow-hidden" >
    <div class="w-lg-50 w-md-80 mx-3 mx-md-auto space-2 space-3--sm space-4--lg text-center text-white">
      <!-- Title -->
      <div class="mt-5 mb-6">
        <h2 class="h1 text-lh-xs pt-2 mb-3">Your next masterpiece<br class="d-none d-lg-inline-block">starts here.</h2>
        <p class="text-white-70 text-lh-sm">Rent and Sublet Creative Spaces.</p>
      </div>
      <!-- End Title -->

      <!-- Search -->
      <%= form_tag spaces_path, method: :get, class: "input-group rounded-pill bg-white overflow-hidden py-2 pl-3 mb-6 align-items-center" do %>
        <%= text_field_tag :query,
          params[:query],
          class: "form-control form-control-sm rounded-pill border-0 mr-1 align-items-center",
          placeholder: "Music Studio in La Condesa, CDMX" %>
                                    %>
        <%= submit_tag "Find", class: "btn btn-sm btn-primary rounded-pill font-weight-medium px-5 py-2 mr-2" %>
      <% end %>
      <!-- End Search -->

      <a class="js-fancybox text-white" href="javascript:;"
        data-src="//youtube.com/embed/5ksBQ9jevAI"
        data-speed="700"
        data-animate-in="zoomIn"
        data-animate-out="zoomOut"
        data-caption="Tropical Experiences with Space">
        See how it works
        <i class="u-icon u-icon--sm u-icon--white-soft rounded-circle ml-2">
          <i class="u-icon__inner svg-icon svg-icon-xs text-white">
            <svg width="24px" height="24px" viewBox="0 0 24 24" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
              <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                <rect x="0" y="0" width="24" height="24"></rect>
                <path d="M9.82866499,18.2771971 L16.5693679,12.3976203 C16.7774696,12.2161036 16.7990211,11.9002555 16.6175044,11.6921539 C16.6029128,11.6754252 16.5872233,11.6596867 16.5705402,11.6450431 L9.82983723,5.72838979 C9.62230202,5.54622572 9.30638833,5.56679309 9.12422426,5.7743283 C9.04415337,5.86555116 9,5.98278612 9,6.10416552 L9,17.9003957 C9,18.1765381 9.22385763,18.4003957 9.5,18.4003957 C9.62084305,18.4003957 9.73759731,18.3566309 9.82866499,18.2771971 Z" fill="#000000"></path>
              </g>
            </svg>
          </i>
        </i>
      </a>
    </div>
  </div>
</main>

app/views/shared/_landing_page.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg" >
      <h1>Your next masterpiece starts here.</h1>
      <h4>Rent and Sublet F'in Dope Creative Spaces.</h4>
       <div class="col-lg pt-3" >
        <div class="form-inline justify-content-center">
      <%= form_tag spaces_path, method: :get do %>
      <%= text_field_tag :query,
          params[:query],
          class: "form-control",
          placeholder: "Find your space"
                                      %>
      <%= submit_tag "Search", class: "btn btn-dark" %>
      <% end %></%>
      </div>
      </div>
    </div>
  </div>
</div>
<footer class="mastfoot">
        <div class="inner">
          <p>Fueled by the brogrammers: @max, @mau, @pedro, @joselito</p>
        </div>
      </footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon sticky-top">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "https://res.cloudinary.com/daak4feoa/image/upload/v1584122944/logo_dbkgiz.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if !user_signed_in? %>
      <li class="nav-item">
          <%= link_to "sign up", new_user_registration_path, class: "nav-link" %>
        </li>
      <% end %>
      <li class="nav-item">
          <%= link_to "list your space", new_space_path, class: "nav-link" %>
        </li>
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "browse", spaces_path, class: "nav-link" %>
        </li>
        <li class="nav-item" id="notifMenu">
          <div id="notif-counter" class="notification" id = "notificationDropdown" data-toggle= "dropdown" aria-haspopup=true aria-expanded=false></div>
          <div class="dropdown-menu dropdown-menu-right notification-box" aria-labelledby="notificationDropdown">
          </div>

        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://res.cloudinary.com/doytwihfl/image/upload/v1582922730/T02NE0241-USA30KXB3-g67656ac417f-512_widzih.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "my profile", user_path(current_user), class: "dropdown-item" %>
            <% if current_user.renter? %>
              <%= link_to "my studioos", own_spaces_spaces_path, class: "dropdown-item" %>
            <% end %>
            <%= link_to "my reservations", own_reservations_reservations_path, class: "dropdown-item" %>
            <%= link_to "log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "log in", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_post_form.html.erb
<div class="container">
  <div class="row justify-content-center listing">
    <div class="col-xs-12 col-sm-8 p-5 col-sm-offset-2 border shadow p-3 mb-5 bg-white rounded">
      <h2>List a new Space</h2><br>
          <%= simple_form_for(@space) do |f| %>
            <%= f.input :name, required: true, autofocus: true %>
            <%= f.input :content, required: true %>
            <%= f.association :tags, label: 'Studio use (eg. painting)', input_html: { class: "select2" } %>
            <%= f.input :address, required: true %>
            <%= f.input :city, required: true %>
            <%= f.input :price_per_day, required: true, label: 'Price per day $(USD)' %>
            <%= f.input :photo, as: :file%><br>
            <%= f.submit "List a space", class: "btn btn-outline-primary btn-lg btn-block" %>
          <% end %>
    </div>
  </div>
</div>